// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdJjcc5hyJfQLW20MIpJOcUYSa0p6E47c',
    appId: '1:595898688935:web:8aef7d31c317f709de0282',
    messagingSenderId: '595898688935',
    projectId: 'mobileapp-ff5e1',
    authDomain: 'mobileapp-ff5e1.firebaseapp.com',
    storageBucket: 'mobileapp-ff5e1.appspot.com',
    measurementId: 'G-95XH53KVH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIDl6v9UhSJwC4XvyXSQb1xLJmXMvNBtQ',
    appId: '1:595898688935:android:56dbd21a5c6bc764de0282',
    messagingSenderId: '595898688935',
    projectId: 'mobileapp-ff5e1',
    storageBucket: 'mobileapp-ff5e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBt47c5wQAZV9fTgxtF8OAxoRjrATiajE',
    appId: '1:595898688935:ios:e5ec07f4f1b50ce4de0282',
    messagingSenderId: '595898688935',
    projectId: 'mobileapp-ff5e1',
    storageBucket: 'mobileapp-ff5e1.appspot.com',
    iosBundleId: 'com.example.calculatorapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBt47c5wQAZV9fTgxtF8OAxoRjrATiajE',
    appId: '1:595898688935:ios:ccdf89e64844fd1cde0282',
    messagingSenderId: '595898688935',
    projectId: 'mobileapp-ff5e1',
    storageBucket: 'mobileapp-ff5e1.appspot.com',
    iosBundleId: 'com.example.calculatorapp.RunnerTests',
  );
}
